print("                  -------------               ")
print("|=================| MAIN PAGE |===============|")
print("|                 -------------               |")
print("|                                             |")
print("|   --------     ----------      ---------    |")
print("|   | Home |     | Search |      | About |    |")
print("|   --------     ----------      ---------    |")
print("|=============================================|")
print("|                                             |")
print("|     Check our Latest Offers in Al Sokhna!   |")
print("|                                             |")
print("|=============================================|")
print("|                                             |")
print("|        Subscribe to our newsletter!         |")
print("|                                             |")
print("|=============================================|")
