print("                  -------------               ")
print("|================| SEARCH PAGE |==============|")
print("|                 -------------               |")
print("|                                             |")
print("|   --------------------------------------    |")
print("|   | type here ...               | Find |    |")
print("|   --------------------------------------    |")
print("|                                             |")
print("|=============================================|")
print("|                                             |")
print("|         (Results will display here)         |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|                                             |")
print("|=============================================|")
